version: '3'

# Source: https://youtu.be/WnlX7w4lHvM

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

# create a topic
# 1. docker exec -it kafka /bin/sh
# 2. cd /opt/kafka
# 3. cd bin
# 4. ./kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic topic-name
# 5. List topics: ./kafka-topics.sh --list --zookeeper zookeeper:2181